version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: my-wake-on-lan_server_1
      APP_PORT: 80
 
  server:
    image: debian:latest
    container_name: my-wake-on-lan
    command: "/bin/bash -c 'chmod +x /scripts/wake_on_lan.sh && /scripts/wake_on_lan.sh'"
    volumes:
      - ./scripts:/scripts
    restart: unless-stopped
    expose:
      - "80"
